[package]
name = "ls-effector-imports"
version = "0.1.2"
edition = "2021"
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ls-effector-types = { workspace = true }
marine-rs-sdk = { workspace = true }
